export default {
  Home: require("../assets/images/ic_home.png"),
  Notifications: require("../assets/images/ic_notify.png"),
  Search: require("../assets/images/ic_srch.png"),
  User: require("../assets/images/ic_user.png"),
  Add: require("../assets/images/ic_add.png"),
  BackArrow: require("../assets/images/ic_back_arrow.png"),
  Logo: require("../assets/images/logo.png"),
  TutorialImage: require("../assets/images/ic_1.png"),
  Google: require("../assets/images/ic_google.png"),
  Apple: require("../assets/images/ic_apple.png"),
  Facebook: require("../assets/images/ic_facebook.png"),
  HomeLogo: require("../assets/images/home_logo.png"),
  Location: require("../assets/images/ic_loc.png"),
  Dots: require("../assets/images/ic_dots.png"),
  Direction: require("../assets/images/ic_direction.png"),
  ProfileUser: require("../assets/images/ic_usrr_1.png"),
  Key: require("../assets/images/ic_key.png"),
  Logout: require("../assets/images/ic_logout.png"),
  Edit: require("../assets/images/ic_edit.png"),
  Cross: require("../assets/images/ic_cross.png"),
  Plus: require("../assets/images/ic_plus.png"),
  BlueTick: require("../assets/images/ic_blue_tick.png"),
  PauseIndicator: require("../assets/images/pause-button.png"),
  GreyTick: require("../assets/images/ic_grey_tick.png"),
  dummySnap: {
    uri: "https://images.pexels.com/photos/2412607/pexels-photo-2412607.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  },
  dummyDp: {
    uri: "https://imageio.forbes.com/specials-images/imageserve/5ed578988b3c370006234c35/0x0.jpg?format=jpg&crop=1031,1031,x43,y49,safe&height=416&width=416&fit=bounds",
  },
};
